# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Foody' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Foody
  
  pod 'Moya', '~> 14.0'
 
  pod 'ImagePicker'
  pod 'SDWebImageSwiftUI'
  pod 'ToastUI'
  pod 'SwifterSwift', '~> 5.2.0'
  pod 'SwiftyUserDefaults', '~> 4.0.0-alpha.1'
  pod 'IQKeyboardManagerSwift', '6.3.0'
  pod 'AlamofireNetworkActivityIndicator', '~> 3.1'
  pod 'UIScrollView-InfiniteScroll', '~> 1.1.0'
  
  pod 'WaterfallGrid', '~> 1.0.0'
  
  # Recommended: Add the Firebase pod
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Storage'

  target 'FoodyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FoodyUITests' do
    # Pods for testing
  end

end
